services:
  backend:
    build: .
    user: root
    command: >
      bash -c "
      chown -R frappe:frappe /home/frappe/frappe-bench &&
      su frappe -c '
        bench set-config -g db_host db &&
        bench set-config -g redis_cache redis://redis:6379 &&
        bench set-config -g redis_queue redis://redis:6379 &&
        bench set-config -g redis_socketio redis://redis:6379 &&
        bench start
      '
      "
    ports:
      - "8000:8000"
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - REDIS_CACHE=redis:6379
      - REDIS_QUEUE=redis:6379
      - REDIS_SOCKETIO=redis:6379

  db:
    image: mariadb:10.6
    healthcheck:
      test: mysqladmin ping -h localhost --password=admin
      interval: 1s
      retries: 15
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=sixth_gear
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:6.0-alpine
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
  sites:
  logs:
